baseURL = "https://andreavitaletti.github.io/blog/"
publishDir = "docs"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-bootstrap4-blog"
[taxonomies]
  tag = "tags"
  category = "categories"
